### PR TITLE
Incorporate outermost labels into seed distribution

### LINKED ISSUE #192: It's not intuitive that a particular fuzz test will get seeded differently depending on the number and order of tests being run
### What happened

I spotted a failing fuzz test in a CI build, and replicated the failure by running it locally with the same seed:

```
$ ./node_modules/.bin/elm-test --fuzz 100 --seed 330613302
...
Given ["",""]

    Just ""
    ╷
    │ Expect.equal
    ╵
    Nothing
...
```

Then I wanted to narrow down the tests being run to examine what's really going on, which made the failure disappear:

```
$ ./node_modules/.bin/elm-test --fuzz 100 --seed 330613302 \
tests/Flux/FluxableSpec.elm
...
TEST RUN PASSED
```

A good colleague of mine pointed out that because seeds are distributed across the entire tests being run, [one should use `only` to isolate the test you want to run](https://github.com/elm-community/elm-test/blob/4.1.1/src/Test/Runner.elm#L194-L200).

### Thoughts

* As a user, it's unintuitive that specifying the seed will not "fix" the randomness of tests in place.
* While `only` works, I'd rather be able to run a single test file, because it takes ~15 seconds to run `elm-test` on our test suite even against a single `only` test on top of already compiled code.
* Is there ever a use case where we want the current behavior when the user has specified a seed? If not, will it be a good idea to not do any distribution at all if we're given a user-supplied seed?
* Maybe this really isn't an issue if #190 is addressed and we have a good fuzzer in place or `elm-test` runs speedily.

### PR DESCRIPTION
**Pull request by rtfeldman**
Fixes #192 by using the outermost label (which is guaranteed to be unique) in conjunction with the initial seed to determine the initial seed used for distribution of tests under that label - instead of using all the seeds that have been distributed up to that point.

Since `node-test-runner` wraps each module's tests in a label with that name (e.g. running `elm-test tests/DreamwriterTests.elm` would wrap an implicit `describe "DreamwriterTests" [ ... ]` around the tests in that module), this change means that if you pass the same `--seed` but change up which files you pass, you'll still get the same results on a per-file basis.

This also means test runners can distribute seeds in parallel within labels, assuming that actually benchmarks better.

### CODE REVIEW

File: src/Test/Runner.elm [hunk 1]
```diff
@@ -230,22 +236,62 @@ distributeSeeds runs seed test =
...
+                            |> Random.step (Random.int 0 Random.maxInt)
+                            |> Tuple.first
+
+                    hashedSeed =
+                        -- Incorporate the originally passed-in seed
+                        (toString intFromSeed ++ description)
+                            -- Hash from String to Int
+                            |> FNV.hashString
+                            -- Convert Int back to Seed
+                            |> Random.initialSeed
```
Comment (rtfeldman) [inline src/Test/Runner.elm]: @Skinney I'd be curious if you have any thoughts on a better way to do this.

Goals:

1. Start with `intFromSeed : Int` and `description : String`
2. End up with a new `Int` that incorporates both of them
3. Have that resulting `Int` not follow any predictable patterns based on its two inputs (this isn't *critical* like in the crypto sense, but it needs to hold true most of the time)

I imagine there's some faster/better way to do this with integer arithmetic, but I was (perhaps unreasonably) worried about overflows and such.

Comment (mgold) [inline src/Test/Runner.elm]: `Random.initialSeed` should be robust to seeds outside the range of unsigned 32-bit ints.

So, do we call `initialSeed` on each file?

**Comment by jwoudenberg** [comment]
This is awesome!

One question: why take the special care to only do the hashing on the outermost labels? Is it an expensive operation? I'm asking because if we'd do that hashing step with every label we encounter it seems we'd already end up with unique seeds for every test, in a way that meets [the only/skip criterium](https://github.com/elm-community/elm-test/blob/fce8c77bbcaad2264dfb8171d97e131f83735fed/src/Test/Runner.elm#L195-L201) by default, which would allow us to get rid of all the other seed distribution logic.

File: src/Test/Runner.elm (hunk 1 above)
Comment (jwoudenberg) [inline src/Test/Runner.elm]: Perhaps use a `Bitwise.xor` to combine them as ints? That shouldn't result in a longer resulting int than what's going in.

**Comment by rtfeldman** [comment]
Performance was one concern, but this way if someone edits a test's description when using `--seed` it'll still reproduce like before.

That seemed like a more compelling use case than anything else I could come up with...I hadn't thought about commenting tests out, but considering `skip` would work better there anyway, I'd default to leaving it this way.

Regardless, super easy to change either way! 😺

File: src/Test/Runner.elm (hunk 1 above)
Comment (rtfeldman) [inline src/Test/Runner.elm]: Ooooh, nice! `Bitwise.xor` sounds like just what the doctor ordered! 😋

Comment (rtfeldman) [inline src/Test/Runner.elm]: > So, do we call `initialSeed` on each file?

In practice the CLI will, yeah. It wraps each file in a `describe moduleNameGoesHere [ ... ]` which will take care of that!

Comment (drathier) [inline src/Test/Runner.elm]: You might end up losing a bit of entropy by xor'ing multiple things together like this, but I think we're fine in this case. If we want to be safer, we could add a large prime and mod 32; see [source code of FNV](https://github.com/Skinney/fnv/blob/1.0.4/src/FNV.elm). This effectively just extends the FNV algorithm by one step.

**Comment by drathier** [comment]
I don't think the performance of the hash function should be considered at all here. It's doing `Char.toCode`, a multiplication, one xor and a mod 32 for each character in the string. They should all be at most a single assembly instruction after V8 is done with them, plus the overhead of how elm outputs javascript. Either way it's fast.

The question should be whether we want the whole description chain to matter, or just the name of the file the testcase is in.

**Comment by mgold** [comment]
Also, if hashing is done once per file, and there are many tests per file (especially if there are fuzz tests), hashing will really not be a large part of the overhead. Honestly I'm more irked by adding another dependency.

**Comment by drathier** [comment]
@mgold I agree about the extra dependency. The whole implementation is 30 lines, and it could be done in 3 lines. There's no reason we couldn't inline that.

**Comment by rtfeldman** [comment]
@drathier you definitely have more expertise in this area than I do!

Want to take a stab at a PR that removes the FNV dependency and incorporates the entropy increase for the `Bitwise.xor` that you mentioned earlier?

**Comment by drathier** [comment]
@rtfeldman sure, I'll do that right after I figure out how this elm-css thing works :)
